# This is a basic workflow to help you get started with Actions

name: Hetzner test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
          
          # No empty commits from web UI smh
jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: TimDaub/hetzner-cloud-deploy-server-action@v2
        with:
          server-name: "gh-actions-server"
          server-image: "ubuntu-20.04"
          server-type: "cx11"
          ssh-key-name: "github"
          hcloud-token: ${{ secrets.HCLOUD_TOKEN }}
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: mkdir -p ~/.ssh/ && ssh-keyscan -H $SERVER_IPV4 >> ~/.ssh/known_hosts
      - run: ls; echo $GITHUB_WORKSPACE
      - run: base="$(basename $PWD)" ; cd .. ; tar -czf "$base.tar.gz" "$base" && ssh root@$SERVER_IPV4 "cat > /tmp/$base.tar.gz" < "$base.tar.gz" && ssh root@$SERVER_IPV4 tar --strip-components=1 -zxf "/tmp/*.tar.gz"
      - run: ssh root@$SERVER_IPV4 ls /tmp ; echo; ls -lah
      - run: ssh root@$SERVER_IPV4 bash ./setup.sh --local --env .hetzner.ci.env
      - run: ssh root@$SERVER_IPV4 cat /root/logs/install.log
      - run: ssh root@$SERVER_IPV4 cat /root/logs/swizzin.log
        
