# This is a basic workflow to help you get started with Actions

name: Hetzner test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: TimDaub/hetzner-cloud-deploy-server-action@v2
        with:
          server-name: "gh-actions-server"
          server-image: "ubuntu-20.04"
          server-type: "cx11"
          ssh-key-name: "github"
          hcloud-token: ${{ secrets.HCLOUD_TOKEN }}
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: mkdir -p ~/.ssh/ && ssh-keyscan -H $SERVER_IPV4 >> ~/.ssh/known_hosts
      - run: ls; echo $GITHUB_WORKSPACE
      - run: base="$(basename $PWD)" ; cd .. ; tar -czf "$base.tar.gz" "$base" && ssh root@$SERVER_IPV4 "cat > /tmp/$base.tar.gz" < "$base.tar.gz" && ssh root@$SERVER_IPV4 tar --strip-components=1 -zxf "/tmp/*.tar.gz"
      - run: ssh root@$SERVER_IPV4 ls /tmp ; echo; ls -lah
      - run: ssh root@$SERVER_IPV4 bash ./setup.sh --pass boopityscoop --env .hetzner.ci.env
      - run: ssh root@$SERVER_IPV4 ls -lah /install
      - run: ssh root@$SERVER_IPV4 cat /root/logs/swizzin.log
        
